version: '3'

services:
  redis:
    image: "redis:alpine"
  web:
    build: ./web
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    links:
      - redis
    ports:
      - "8000:8000"
    depends_on:
      - redis
      
  celery:
    build: ./web
    command: celery -A perfproject worker -l info
    links:
      - redis
    depends_on:
      - redis
      
  celery-beat:
    build: ./web
    command: celery -A perfproject beat -l info
    links:
      - redis
    depends_on:
      - redis

