version: '3'

services:
  redis:
    image: "redis:alpine"

  web:
    build: ./web
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    links:
      - redis
    volumes:
      - ./web/:/perfserv/code/
    expose:
      - "8000"
    depends_on:
      - redis

  celery:
    build:
      context: ./web
      dockerfile: CeleryDockerfile
    command: celery -A perfproject worker -l info
    links:
      - redis
    depends_on:
      - redis

  celery-beat:
    build:
      context: ./web
      dockerfile: CeleryDockerfile
    command: celery -A perfproject beat -l info
    links:
      - redis
    depends_on:
      - redis

  nginx:
    restart: unless-stopped
    build: ./nginx/
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/perfapp/static/:/static
    links:
      - web:web
