# Generated by Django 2.1.5 on 2019-04-03 07:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfapp', '0002_auto_20190403_0710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attempts',
            new_name='Attempt',
        ),
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
        migrations.RenameModel(
            old_name='Servers',
            new_name='Server',
        ),
    ]
