# Generated by Django 2.1.5 on 2019-04-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0003_auto_20190403_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_score_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
