# Generated by Django 2.1.5 on 2019-04-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0005_auto_20190412_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deletable',
            field=models.BooleanField(default=False),
        ),
    ]
