# Generated by Django 2.1.5 on 2019-04-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0006_job_deletable'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='note_field',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
