# Generated by Django 2.1.5 on 2019-04-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0007_job_note_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='note_field',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
