# Generated by Django 2.1.5 on 2019-04-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0008_auto_20190413_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
