# Generated by Django 2.1.5 on 2019-04-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0009_auto_20190413_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jid',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
