# Generated by Django 2.1.5 on 2019-04-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0010_job_jid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
