# Generated by Django 2.1.5 on 2019-04-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0011_auto_20190414_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='time_stamp',
            new_name='time_created',
        ),
        migrations.AddField(
            model_name='job',
            name='time_started',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
