# Generated by Django 2.1.5 on 2019-04-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0014_job_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='errors',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
