# Generated by Django 2.1.5 on 2019-04-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0015_job_errors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='FilterMain',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Filter_c',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Filter_h',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Makefile',
        ),
        migrations.RemoveField(
            model_name='job',
            name='config',
        ),
        migrations.RemoveField(
            model_name='job',
            name='cs1300_c',
        ),
        migrations.RemoveField(
            model_name='job',
            name='cs1300_h',
        ),
        migrations.AddField(
            model_name='job',
            name='directory_path',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
