# Generated by Django 2.1.5 on 2019-04-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0017_remove_job_directory_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='rel_id',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
