# Generated by Django 2.1.5 on 2019-04-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0018_attempt_rel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='fail_task',
            field=models.BooleanField(default=False),
        ),
    ]
