# Generated by Django 2.1.5 on 2019-05-01 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import perfapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfapp', '0020_auto_20190429_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_job_id', models.PositiveSmallIntegerField()),
                ('err_file', models.FileField(default=None, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='errors',
            field=models.FileField(blank=True, default=None, null=True),
        ),
    ]
