# Generated by Django 2.1.5 on 2019-05-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0021_auto_20190430_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='errors',
        ),
    ]
