# Generated by Django 2.1.5 on 2019-05-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0023_auto_20190501_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='err_file',
            new_name='errors',
        ),
        migrations.RemoveField(
            model_name='job',
            name='percent_complete',
        ),
    ]
