# Generated by Django 2.1.5 on 2019-05-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0024_auto_20190501_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
