# Generated by Django 2.1.5 on 2019-05-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0026_remove_error_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='errors',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
