# Generated by Django 2.1.5 on 2019-05-03 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0027_error_errors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='fail_task',
        ),
    ]
