# Generated by Django 2.1.5 on 2019-05-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0031_auto_20190505_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cur_action',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
