# Generated by Django 2.1.5 on 2019-05-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0032_job_cur_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cur_action',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
