# Generated by Django 2.1.5 on 2019-05-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0033_auto_20190505_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
