# Generated by Django 2.1.5 on 2019-05-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0035_auto_20190509_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='note_field',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='note_field',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
