# Generated by Django 2.1.7 on 2019-05-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfapp', '0036_auto_20190509_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
